#######################################################################
#  This is the makefile to create a library of the test matrix
#  generators used in LAPACK.  The files are organized as follows:
#
#     SCATGEN  -- Auxiliary routines called from single precision
#     DZATGEN  -- Auxiliary routines called from double precision
#     SMATGEN  -- Single precision real matrix generation routines
#     CMATGEN  -- Single precision complex matrix generation routines
#     DMATGEN  -- Double precision real matrix generation routines
#     ZMATGEN  -- Double precision complex matrix generation routines
#
#  The library can be set up to include routines for any combination
#  of the four precisions.  To create or add to the library, enter make
#  followed by one or more of the precisions desired.  Some examples:
#       make single
#       make single complex
#       make single double complex complex16
#  Alternatively, the command
#       make
#  without any arguments creates a library of all four precisions.
#  The library is called
#       tmglib.lib
#  and is created at the LAPACK directory level.
#
#  To remove the object files after the library is created, enter
#       make cleanobj
#  On some systems, you can force the source files to be recompiled by
#  entering (for example)
#       make single FRC=FRC
#
#######################################################################

TOPSRCDIR = ..\..
!INCLUDE $(TOPSRCDIR)\make.win

.SUFFIXES: .f .obj

.f.obj:
	$(FC) $(FFLAGS) /c /Fo$@ $<

SCATGEN = slatm1.obj slatm7.obj slaran.obj slarnd.obj

SMATGEN = slatms.obj slatme.obj slatmr.obj slatmt.obj \
   slagge.obj slagsy.obj slakf2.obj slarge.obj slaror.obj slarot.obj slatm2.obj \
   slatm3.obj slatm5.obj slatm6.obj slahilb.obj

CMATGEN = clatms.obj clatme.obj clatmr.obj clatmt.obj \
   clagge.obj claghe.obj clagsy.obj clakf2.obj clarge.obj claror.obj clarot.obj \
   clatm1.obj clarnd.obj clatm2.obj clatm3.obj clatm5.obj clatm6.obj clahilb.obj

DZATGEN = dlatm1.obj dlatm7.obj dlaran.obj dlarnd.obj

DMATGEN = dlatms.obj dlatme.obj dlatmr.obj dlatmt.obj \
   dlagge.obj dlagsy.obj dlakf2.obj dlarge.obj dlaror.obj dlarot.obj dlatm2.obj \
   dlatm3.obj dlatm5.obj dlatm6.obj dlahilb.obj

ZMATGEN = zlatms.obj zlatme.obj zlatmr.obj zlatmt.obj \
   zlagge.obj zlaghe.obj zlagsy.obj zlakf2.obj zlarge.obj zlaror.obj zlarot.obj \
   zlatm1.obj zlarnd.obj zlatm2.obj zlatm3.obj zlatm5.obj zlatm6.obj zlahilb.obj

all: $(TMGLIB)

ALLOBJ = $(SMATGEN) $(CMATGEN) $(SCATGEN) $(DMATGEN) $(ZMATGEN) \
	$(DZATGEN)

$(TMGLIB): $(ALLOBJ)
	$(AR) $(ARFLAGS) /OUT:$@ $**
	$(RANLIB) $@

single: $(SMATGEN) $(SCATGEN)
	$(AR) $(ARFLAGS) /OUT:$(TMGLIB) $**
	$(RANLIB) $(TMGLIB)

complex: $(CMATGEN) $(SCATGEN)
	$(AR) $(ARFLAGS) /OUT:$(TMGLIB) $**
	$(RANLIB) $(TMGLIB)

double: $(DMATGEN) $(DZATGEN)
	$(AR) $(ARFLAGS) /OUT:$(TMGLIB) $**
	$(RANLIB) $(TMGLIB)

complex16: $(ZMATGEN) $(DZATGEN)
	$(AR) $(ARFLAGS) /OUT:$(TMGLIB) $**
	$(RANLIB) $(TMGLIB)

!IFDEF FRC
$(SCATGEN): $(FRC)
$(SMATGEN): $(FRC)
$(CMATGEN): $(FRC)
$(DZATGEN): $(FRC)
$(DMATGEN): $(FRC)
$(ZMATGEN): $(FRC)

FRC:
	@FRC=$(FRC)
!ENDIF

clean: cleanobj cleanlib

cleanobj:
	DEL /F /Q *.obj

cleanlib:
	DEL /F /Q $(TMGLIB)

slaran.obj: slaran.f
	$(FC) $(FFLAGS_NOOPT) /c /Fo$@ $**

dlaran.obj: dlaran.f
	$(FC) $(FFLAGS_NOOPT) /c /Fo$@ $**
