#######################################################################
#  This makefile runs the test programs for the linear equation routines
#  and the eigenvalue routines in LAPACK.  The test output files
#  are grouped as follows:
#
#       SLINTST,SEIGTST  -- Single precision real test routines
#       CLINTST,CEIGTST  -- Single precision complex test routines
#       DLINTST,DEIGTST  -- Double precision real test routines
#       ZLINTST,ZEIGTST  -- Double precision complex test routines
#
#  Test programs can be executed for all or some of the four different
#  precisions.  Enter 'make' followed by one or more of the data types
#  desired.
#  Some examples:
#       make single
#       make single complex
#       make single double complex complex16
#  Alternatively, the command
#       make
#  without any arguments runs all eight test programs.
#  The executable files are called:
#       xlintsts, xlintstd, xlintstc, and xlintstz for LIN
#       xeigtsts, xeigtstd, xeigtstc, and xeigtstz for EIG
#
#  To remove the output files after the tests have been run, enter
#       make cleantest
#
#  To re-run specific tests after a make, enter (for example):
#       'rm ssvd.out; make'  or:
#       'make ssvd.out' or:
#       'touch svd.in; make' (to re-run the single precision SVD tests.)
#
#       'rm *svd.out; make'  (to re-run all the SVD tests.)
#
#######################################################################

TOPSRCDIR = ..
!INCLUDE $(TOPSRCDIR)\make.win

all: single complex double complex16 singleproto doubleproto complexproto complex16proto

SEIGTST= snep.out \
         ssep.out \
         sse2.out \
         ssvd.out \
         sec.out \
         sed.out \
         sgg.out \
         sgd.out \
         ssb.out \
         ssg.out \
         sbal.out \
         sbak.out \
         sgbal.out \
         sgbak.out \
         sbb.out \
         sglm.out \
         sgqr.out \
         sgsv.out \
         scsd.out \
         slse.out

SDMDEIGTST= sdmd.out

CEIGTST= cnep.out \
         csep.out \
         cse2.out \
         csvd.out \
         cec.out \
         ced.out \
         cgg.out \
         cgd.out \
         csb.out \
         csg.out \
         cbal.out \
         cbak.out \
         cgbal.out \
         cgbak.out \
         cbb.out \
         cglm.out \
         cgqr.out \
         cgsv.out \
         ccsd.out \
         clse.out

CDMDEIGTST= cdmd.out

DEIGTST= dnep.out \
         dsep.out \
         dse2.out \
         dsvd.out \
         dec.out \
         ded.out \
         dgg.out \
         dgd.out \
         dsb.out \
         dsg.out \
         dbal.out \
         dbak.out \
         dgbal.out \
         dgbak.out \
         dbb.out \
         dglm.out \
         dgqr.out \
         dgsv.out \
         dcsd.out \
         dlse.out

DDMDEIGTST= ddmd.out

ZEIGTST= znep.out \
         zsep.out \
         zse2.out \
         zsvd.out \
         zec.out \
         zed.out \
         zgg.out \
         zgd.out \
         zsb.out \
         zsg.out \
         zbal.out \
         zbak.out \
         zgbal.out \
         zgbak.out \
         zbb.out \
         zglm.out \
         zgqr.out \
         zgsv.out \
         zcsd.out \
         zlse.out

ZDMDEIGTST= zdmd.out

SLINTST= stest.out

SLINTSTPROTO= stest_rfp.out

CLINTST= ctest.out

CLINTSTPROTO= ctest_rfp.out

DLINTST= dtest.out

DLINTSTPROTO= dstest.out dtest_rfp.out

ZLINTST= ztest.out

ZLINTSTPROTO= zctest.out ztest_rfp.out

single:         $(SLINTST) $(SEIGTST) $(SDMDEIGTST)
complex:        $(CLINTST) $(CEIGTST) $(CDMDEIGTST)
double:         $(DLINTST) $(DEIGTST) $(DDMDEIGTST)
complex16:      $(ZLINTST) $(ZEIGTST) $(ZDMDEIGTST)

singleproto:    $(SLINTSTPROTO)
complexproto:   $(CLINTSTPROTO)
doubleproto:    $(DLINTSTPROTO)
complex16proto: $(ZLINTSTPROTO)

#
# ======== SINGLE LIN TESTS ===========================

stest.out: stest.in LIN\xlintsts.exe
	@echo Testing REAL LAPACK linear equation routines
	LIN\xlintsts.exe < stest.in > $@ 2>&1
#
# ======== COMPLEX LIN TESTS ==========================

ctest.out: ctest.in LIN\xlintstc.exe
	@echo Testing COMPLEX LAPACK linear equation routines
	LIN\xlintstc.exe < ctest.in > $@ 2>&1
#
# ======== DOUBLE LIN TESTS ===========================

dtest.out: dtest.in LIN\xlintstd.exe
	@echo Testing DOUBLE PRECISION LAPACK linear equation routines
	LIN\xlintstd.exe < dtest.in > $@ 2>&1
#
# ======== COMPLEX16 LIN TESTS ========================

ztest.out: ztest.in LIN\xlintstz.exe
	@echo Testing COMPLEX16 LAPACK linear equation routines
	LIN\xlintstz.exe < ztest.in > $@ 2>&1
#
# ======== SINGLE-DOUBLE PROTO LIN TESTS ==============

dstest.out: dstest.in LIN\xlintstds.exe
	@echo Testing SINGLE-DOUBLE PRECISION LAPACK prototype linear equation routines
	LIN\xlintstds.exe < dstest.in > $@ 2>&1
#
# ======== COMPLEX-COMPLEX16 LIN TESTS ========================

zctest.out: zctest.in LIN\xlintstzc.exe
	@echo Testing COMPLEX-COMPLEX16 LAPACK prototype linear equation routines
	LIN\xlintstzc.exe < zctest.in > $@ 2>&1
#
# ======== SINGLE RFP LIN TESTS ========================

stest_rfp.out: stest_rfp.in LIN\xlintstrfs.exe
	@echo Testing REAL LAPACK RFP prototype linear equation routines
	LIN\xlintstrfs.exe < stest_rfp.in > $@ 2>&1
#
# ======== COMPLEX16 RFP LIN TESTS ========================

dtest_rfp.out: dtest_rfp.in LIN\xlintstrfd.exe
	@echo Testing DOUBLE PRECISION LAPACK RFP prototype linear equation routines
	LIN\xlintstrfd.exe < dtest_rfp.in > $@ 2>&1
#
# ======== COMPLEX16 RFP LIN TESTS ========================

ctest_rfp.out: ctest_rfp.in LIN\xlintstrfc.exe
	@echo Testing COMPLEX LAPACK RFP prototype linear equation routines
	LIN\xlintstrfc.exe < ctest_rfp.in > $@ 2>&1
#
# ======== COMPLEX16 RFP LIN TESTS ========================

ztest_rfp.out: ztest_rfp.in LIN\xlintstrfz.exe
	@echo Testing COMPLEX16 LAPACK RFP prototype linear equation routines
	LIN\xlintstrfz.exe < ztest_rfp.in > $@ 2>&1
#
#
# ======== SINGLE EIG TESTS ===========================
#

snep.out: nep.in EIG\xeigtsts.exe
	@echo NEP: Testing Nonsymmetric Eigenvalue Problem routines
	EIG\xeigtsts.exe < nep.in > $@ 2>&1

ssep.out: sep.in EIG\xeigtsts.exe
	@echo SEP: Testing Symmetric Eigenvalue Problem routines
	EIG\xeigtsts.exe < sep.in > $@ 2>&1

sse2.out: se2.in EIG\xeigtsts.exe
	@echo SEP: Testing Symmetric Eigenvalue Problem routines
	EIG\xeigtsts.exe < se2.in > $@ 2>&1

ssvd.out: svd.in EIG\xeigtsts.exe
	@echo SVD: Testing Singular Value Decomposition routines
	EIG\xeigtsts.exe < svd.in > $@ 2>&1

sec.out: sec.in EIG\xeigtsts.exe
	@echo SEC: Testing REAL Eigen Condition Routines
	EIG\xeigtsts.exe < sec.in > $@ 2>&1

sed.out: sed.in EIG\xeigtsts.exe
	@echo SEV: Testing REAL Nonsymmetric Eigenvalue Driver
	EIG\xeigtsts.exe < sed.in > $@ 2>&1

sgg.out: sgg.in EIG\xeigtsts.exe
	@echo SGG: Testing REAL Nonsymmetric Generalized Eigenvalue Problem routines
	EIG\xeigtsts.exe < sgg.in > $@ 2>&1

sgd.out: sgd.in EIG\xeigtsts.exe
	@echo SGD: Testing REAL Nonsymmetric Generalized Eigenvalue Problem driver routines
	EIG\xeigtsts.exe < sgd.in > $@ 2>&1

ssb.out: ssb.in EIG\xeigtsts.exe
	@echo SSB: Testing REAL Symmetric Eigenvalue Problem routines
	EIG\xeigtsts.exe < ssb.in > $@ 2>&1

ssg.out: ssg.in EIG\xeigtsts.exe
	@echo SSG: Testing REAL Symmetric Generalized Eigenvalue Problem routines
	EIG\xeigtsts.exe < ssg.in > $@ 2>&1

sbal.out: sbal.in EIG\xeigtsts.exe
	@echo SGEBAL: Testing the balancing of a REAL general matrix
	EIG\xeigtsts.exe < sbal.in > $@ 2>&1

sbak.out: sbak.in EIG\xeigtsts.exe
	@echo SGEBAK: Testing the back transformation of a REAL balanced matrix
	EIG\xeigtsts.exe < sbak.in > $@ 2>&1

sgbal.out: sgbal.in EIG\xeigtsts.exe
	@echo SGGBAL: Testing the balancing of a pair of REAL general matrices
	EIG\xeigtsts.exe < sgbal.in > $@ 2>&1

sgbak.out: sgbak.in EIG\xeigtsts.exe
	@echo SGGBAK: Testing the back transformation of a pair of REAL balanced matrices
	EIG\xeigtsts.exe < sgbak.in > $@ 2>&1

sbb.out: sbb.in EIG\xeigtsts.exe
	@echo SBB: Testing banded Singular Value Decomposition routines
	EIG\xeigtsts.exe < sbb.in > $@ 2>&1

sglm.out: glm.in EIG\xeigtsts.exe
	@echo GLM: Testing Generalized Linear Regression Model routines
	EIG\xeigtsts.exe < glm.in > $@ 2>&1

sgqr.out: gqr.in EIG\xeigtsts.exe
	@echo GQR: Testing Generalized QR and RQ factorization routines
	EIG\xeigtsts.exe < gqr.in > $@ 2>&1

sgsv.out: gsv.in EIG\xeigtsts.exe
	@echo GSV: Testing Generalized Singular Value Decomposition routines
	EIG\xeigtsts.exe < gsv.in > $@ 2>&1

scsd.out: csd.in EIG\xeigtsts.exe
	@echo CSD: Testing CS Decomposition routines
	EIG\xeigtsts.exe < csd.in > $@ 2>&1

slse.out: lse.in EIG\xeigtsts.exe
	@echo LSE: Testing Constrained Linear Least Squares routines
	EIG\xeigtsts.exe < lse.in > $@ 2>&1

sdmd.out: sdmd.in EIG\xdmdeigtsts.exe
	@echo DMD: Testing Dynamic Mode Decomposition routines
	EIG\xdmdeigtsts.exe < sdmd.in > $@ 2>&1
#
# ======== COMPLEX EIG TESTS ===========================

cnep.out: nep.in EIG\xeigtstc.exe
	@echo NEP: Testing Nonsymmetric Eigenvalue Problem routines
	EIG\xeigtstc.exe < nep.in > $@ 2>&1

csep.out: sep.in EIG\xeigtstc.exe
	@echo SEP: Testing Symmetric Eigenvalue Problem routines
	EIG\xeigtstc.exe < sep.in > $@ 2>&1

cse2.out: se2.in EIG\xeigtstc.exe
	@echo SEP: Testing Symmetric Eigenvalue Problem routines
	EIG\xeigtstc.exe < se2.in > $@ 2>&1

csvd.out: svd.in EIG\xeigtstc.exe
	@echo SVD: Testing Singular Value Decomposition routines
	EIG\xeigtstc.exe < svd.in > $@ 2>&1

cec.out: cec.in EIG\xeigtstc.exe
	@echo CEC: Testing COMPLEX Eigen Condition Routines
	EIG\xeigtstc.exe < cec.in > $@ 2>&1

ced.out: ced.in EIG\xeigtstc.exe
	@echo CES: Testing COMPLEX Nonsymmetric Schur Form Driver
	EIG\xeigtstc.exe < ced.in > $@ 2>&1

cgg.out: cgg.in EIG\xeigtstc.exe
	@echo CGG: Testing COMPLEX Nonsymmetric Generalized Eigenvalue Problem routines
	EIG\xeigtstc.exe < cgg.in > $@ 2>&1

cgd.out: cgd.in EIG\xeigtstc.exe
	@echo CGD: Testing COMPLEX Nonsymmetric Generalized Eigenvalue Problem driver routines
	EIG\xeigtstc.exe < cgd.in > $@ 2>&1

csb.out: csb.in EIG\xeigtstc.exe
	@echo CHB: Testing Hermitian Eigenvalue Problem routines
	EIG\xeigtstc.exe < csb.in > $@ 2>&1

csg.out: csg.in EIG\xeigtstc.exe
	@echo CSG: Testing Symmetric Generalized Eigenvalue Problem routines
	EIG\xeigtstc.exe < csg.in > $@ 2>&1

cbal.out: cbal.in EIG\xeigtstc.exe
	@echo CGEBAL: Testing the balancing of a COMPLEX general matrix
	EIG\xeigtstc.exe < cbal.in > $@ 2>&1

cbak.out: cbak.in EIG\xeigtstc.exe
	@echo CGEBAK: Testing the back transformation of a COMPLEX balanced matrix
	EIG\xeigtstc.exe < cbak.in > $@ 2>&1

cgbal.out: cgbal.in EIG\xeigtstc.exe
	@echo CGGBAL: Testing the balancing of a pair of COMPLEX general matrices
	EIG\xeigtstc.exe < cgbal.in > $@ 2>&1

cgbak.out: cgbak.in EIG\xeigtstc.exe
	@echo CGGBAK: Testing the back transformation of a pair of COMPLEX balanced matrices
	EIG\xeigtstc.exe < cgbak.in > $@ 2>&1

cbb.out: cbb.in EIG\xeigtstc.exe
	@echo CBB: Testing banded Singular Value Decomposition routines
	EIG\xeigtstc.exe < cbb.in > $@ 2>&1

cglm.out: glm.in EIG\xeigtstc.exe
	@echo GLM: Testing Generalized Linear Regression Model routines
	EIG\xeigtstc.exe < glm.in > $@ 2>&1

cgqr.out: gqr.in EIG\xeigtstc.exe
	@echo GQR: Testing Generalized QR and RQ factorization routines
	EIG\xeigtstc.exe < gqr.in > $@ 2>&1

cgsv.out: gsv.in EIG\xeigtstc.exe
	@echo GSV: Testing Generalized Singular Value Decomposition routines
	EIG\xeigtstc.exe < gsv.in > $@ 2>&1

ccsd.out: csd.in EIG\xeigtstc.exe
	@echo CSD: Testing CS Decomposition routines
	EIG\xeigtstc.exe < csd.in > $@ 2>&1

clse.out: lse.in EIG\xeigtstc.exe
	@echo LSE: Testing Constrained Linear Least Squares routines
	EIG\xeigtstc.exe < lse.in > $@ 2>&1

cdmd.out: cdmd.in EIG\xdmdeigtstc.exe
	@echo DMD: Testing Dynamic Mode Decomposition routines
	EIG\xdmdeigtstc.exe < cdmd.in > $@ 2>&1
#
# ======== DOUBLE EIG TESTS ===========================

dnep.out: nep.in EIG\xeigtstd.exe
	@echo NEP: Testing Nonsymmetric Eigenvalue Problem routines
	EIG\xeigtstd.exe < nep.in > $@ 2>&1

dsep.out: sep.in EIG\xeigtstd.exe
	@echo SEP: Testing Symmetric Eigenvalue Problem routines
	EIG\xeigtstd.exe < sep.in > $@ 2>&1

dse2.out: se2.in EIG\xeigtstd.exe
	@echo SEP: Testing Symmetric Eigenvalue Problem routines
	EIG\xeigtstd.exe < se2.in > $@ 2>&1

dsvd.out: svd.in EIG\xeigtstd.exe
	@echo SVD: Testing Singular Value Decomposition routines
	EIG\xeigtstd.exe < svd.in > $@ 2>&1

dec.out: dec.in EIG\xeigtstd.exe
	@echo DEC: Testing DOUBLE PRECISION Eigen Condition Routines
	EIG\xeigtstd.exe < dec.in > $@ 2>&1

ded.out: ded.in EIG\xeigtstd.exe
	@echo DEV: Testing DOUBLE PRECISION Nonsymmetric Eigenvalue Driver
	EIG\xeigtstd.exe < ded.in > $@ 2>&1

dgg.out: dgg.in EIG\xeigtstd.exe
	@echo DGG: Testing DOUBLE PRECISION Nonsymmetric Generalized Eigenvalue Problem routines
	EIG\xeigtstd.exe < dgg.in > $@ 2>&1

dgd.out: dgd.in EIG\xeigtstd.exe
	@echo DGD: Testing DOUBLE PRECISION Nonsymmetric Generalized Eigenvalue Problem driver routines
	EIG\xeigtstd.exe < dgd.in > $@ 2>&1

dsb.out: dsb.in EIG\xeigtstd.exe
	@echo DSB: Testing DOUBLE PRECISION Symmetric Eigenvalue Problem routines
	EIG\xeigtstd.exe < dsb.in > $@ 2>&1

dsg.out: dsg.in EIG\xeigtstd.exe
	@echo DSG: Testing DOUBLE PRECISION Symmetric Generalized Eigenvalue Problem routines
	EIG\xeigtstd.exe < dsg.in > $@ 2>&1

dbal.out: dbal.in EIG\xeigtstd.exe
	@echo DGEBAL: Testing the balancing of a DOUBLE PRECISION general matrix
	EIG\xeigtstd.exe < dbal.in > $@ 2>&1

dbak.out: dbak.in EIG\xeigtstd.exe
	@echo DGEBAK: Testing the back transformation of a DOUBLE PRECISION balanced matrix
	EIG\xeigtstd.exe < dbak.in > $@ 2>&1

dgbal.out: dgbal.in EIG\xeigtstd.exe
	@echo DGGBAL: Testing the balancing of a pair of DOUBLE PRECISION general matrices
	EIG\xeigtstd.exe < dgbal.in > $@ 2>&1

dgbak.out: dgbak.in EIG\xeigtstd.exe
	@echo DGGBAK: Testing the back transformation of a pair of DOUBLE PRECISION balanced matrices
	EIG\xeigtstd.exe < dgbak.in > $@ 2>&1

dbb.out: dbb.in EIG\xeigtstd.exe
	@echo DBB: Testing banded Singular Value Decomposition routines
	EIG\xeigtstd.exe < dbb.in > $@ 2>&1

dglm.out: glm.in EIG\xeigtstd.exe
	@echo GLM: Testing Generalized Linear Regression Model routines
	EIG\xeigtstd.exe < glm.in > $@ 2>&1

dgqr.out: gqr.in EIG\xeigtstd.exe
	@echo GQR: Testing Generalized QR and RQ factorization routines
	EIG\xeigtstd.exe < gqr.in > $@ 2>&1

dgsv.out: gsv.in EIG\xeigtstd.exe
	@echo GSV: Testing Generalized Singular Value Decomposition routines
	EIG\xeigtstd.exe < gsv.in > $@ 2>&1

dcsd.out: csd.in EIG\xeigtstd.exe
	@echo CSD: Testing CS Decomposition routines
	EIG\xeigtstd.exe < csd.in > $@ 2>&1

dlse.out: lse.in EIG\xeigtstd.exe
	@echo LSE: Testing Constrained Linear Least Squares routines
	EIG\xeigtstd.exe < lse.in > $@ 2>&1

ddmd.out: ddmd.in EIG\xdmdeigtstd.exe
	@echo DMD: Testing Dynamic Mode Decomposition routines
	EIG\xdmdeigtstd.exe < ddmd.in > $@ 2>&1
#
# ======== COMPLEX16 EIG TESTS ===========================

znep.out: nep.in EIG\xeigtstz.exe
	@echo NEP: Testing Nonsymmetric Eigenvalue Problem routines
	EIG\xeigtstz.exe < nep.in > $@ 2>&1

zsep.out: sep.in EIG\xeigtstz.exe
	@echo SEP: Testing Symmetric Eigenvalue Problem routines
	EIG\xeigtstz.exe < sep.in > $@ 2>&1

zse2.out: se2.in EIG\xeigtstz.exe
	@echo SEP: Testing Symmetric Eigenvalue Problem routines
	EIG\xeigtstz.exe < se2.in > $@ 2>&1

zsvd.out: svd.in EIG\xeigtstz.exe
	@echo SVD: Testing Singular Value Decomposition routines
	EIG\xeigtstz.exe < svd.in > $@ 2>&1

zec.out: zec.in EIG\xeigtstz.exe
	@echo ZEC: Testing COMPLEX16 Eigen Condition Routines
	EIG\xeigtstz.exe < zec.in > $@ 2>&1

zed.out: zed.in EIG\xeigtstz.exe
	@echo ZES: Testing COMPLEX16 Nonsymmetric Schur Form Driver
	EIG\xeigtstz.exe < zed.in > $@ 2>&1

zgg.out: zgg.in EIG\xeigtstz.exe
	@echo ZGG: Testing COMPLEX16 Nonsymmetric Generalized Eigenvalue Problem routines
	EIG\xeigtstz.exe < zgg.in > $@ 2>&1

zgd.out: zgd.in EIG\xeigtstz.exe
	@echo ZGD: Testing COMPLEX16 Nonsymmetric Generalized Eigenvalue Problem driver routines
	EIG\xeigtstz.exe < zgd.in > $@ 2>&1

zsb.out: zsb.in EIG\xeigtstz.exe
	@echo ZHB: Testing Hermitian Eigenvalue Problem routines
	EIG\xeigtstz.exe < zsb.in > $@ 2>&1

zsg.out: zsg.in EIG\xeigtstz.exe
	@echo ZSG: Testing Symmetric Generalized Eigenvalue Problem routines
	EIG\xeigtstz.exe < zsg.in > $@ 2>&1

zbal.out: zbal.in EIG\xeigtstz.exe
	@echo ZGEBAL: Testing the balancing of a COMPLEX16 general matrix
	EIG\xeigtstz.exe < zbal.in > $@ 2>&1

zbak.out: zbak.in EIG\xeigtstz.exe
	@echo ZGEBAK: Testing the back transformation of a COMPLEX16 balanced matrix
	EIG\xeigtstz.exe < zbak.in > $@ 2>&1

zgbal.out: zgbal.in EIG\xeigtstz.exe
	@echo ZGGBAL: Testing the balancing of a pair of COMPLEX general matrices
	EIG\xeigtstz.exe < zgbal.in > $@ 2>&1

zgbak.out: zgbak.in EIG\xeigtstz.exe
	@echo ZGGBAK: Testing the back transformation of a pair of COMPLEX16 balanced matrices
	EIG\xeigtstz.exe < zgbak.in > $@ 2>&1

zbb.out: zbb.in EIG\xeigtstz.exe
	@echo ZBB: Testing banded Singular Value Decomposition routines
	EIG\xeigtstz.exe < zbb.in > $@ 2>&1

zglm.out: glm.in EIG\xeigtstz.exe
	@echo GLM: Testing Generalized Linear Regression Model routines
	EIG\xeigtstz.exe < glm.in > $@ 2>&1

zgqr.out: gqr.in EIG\xeigtstz.exe
	@echo GQR: Testing Generalized QR and RQ factorization routines
	EIG\xeigtstz.exe < gqr.in > $@ 2>&1

zgsv.out: gsv.in EIG\xeigtstz.exe
	@echo GSV: Testing Generalized Singular Value Decomposition routines
	EIG\xeigtstz.exe < gsv.in > $@ 2>&1

zcsd.out: csd.in EIG\xeigtstz.exe
	@echo CSD: Testing CS Decomposition routines
	EIG\xeigtstz.exe < csd.in > $@ 2>&1

zlse.out: lse.in EIG\xeigtstz.exe
	@echo LSE: Testing Constrained Linear Least Squares routines
	EIG\xeigtstz.exe < lse.in > $@ 2>&1

zdmd.out: zdmd.in EIG\xdmdeigtstz.exe
	@echo DMD: Testing Dynamic Mode Decomposition routines
	EIG\xdmdeigtstz.exe < zdmd.in > $@ 2>&1
# ==============================================================================

LIN\xlintsts.exe: $(FRCLIN) $(FRC)
	pushd LIN && $(MAKE) /NOLOGO /F Makefile.win xlintsts.exe && popd

LIN\xlintstc.exe: $(FRCLIN) $(FRC)
	pushd LIN && $(MAKE) /NOLOGO /F Makefile.win xlintstc.exe && popd

LIN\xlintstd.exe: $(FRCLIN) $(FRC)
	pushd LIN && $(MAKE) /NOLOGO /F Makefile.win xlintstd.exe && popd

LIN\xlintstz.exe: $(FRCLIN) $(FRC)
	pushd LIN && $(MAKE) /NOLOGO /F Makefile.win xlintstz.exe && popd

LIN\xlintstrfs.exe: $(FRCLIN) $(FRC)
	pushd LIN && $(MAKE) /NOLOGO /F Makefile.win xlintstrfs.exe && popd

LIN\xlintstrfc.exe: $(FRCLIN) $(FRC)
	pushd LIN && $(MAKE) /NOLOGO /F Makefile.win xlintstrfc.exe && popd

LIN\xlintstrfd.exe: $(FRCLIN) $(FRC)
	pushd LIN && $(MAKE) /NOLOGO /F Makefile.win xlintstrfd.exe && popd

LIN\xlintstrfz.exe: $(FRCLIN) $(FRC)
	pushd LIN && $(MAKE) /NOLOGO /F Makefile.win xlintstrfz.exe && popd

LIN\xlintstds.exe: $(FRCLIN) $(FRC)
	pushd LIN && $(MAKE) /NOLOGO /F Makefile.win xlintstds.exe && popd

LIN\xlintstzc.exe: $(FRCLIN) $(FRC)
	pushd LIN && $(MAKE) /NOLOGO /F Makefile.win xlintstzc.exe && popd

EIG\xeigtsts.exe: $(FRCEIG) $(FRC)
	pushd EIG && $(MAKE) /NOLOGO /F Makefile.win xeigtsts.exe && popd

EIG\xdmdeigtsts.exe: $(FRCEIG) $(FRC)
	pushd EIG && $(MAKE) /NOLOGO /F Makefile.win xdmdeigtsts.exe && popd

EIG\xeigtstc.exe: $(FRCEIG) $(FRC)
	pushd EIG && $(MAKE) /NOLOGO /F Makefile.win xeigtstc.exe && popd

EIG\xdmdeigtstc.exe: $(FRCEIG) $(FRC)
	pushd EIG && $(MAKE) /NOLOGO /F Makefile.win xdmdeigtstc.exe && popd

EIG\xeigtstd.exe: $(FRCEIG) $(FRC)
	pushd EIG && $(MAKE) /NOLOGO /F Makefile.win xeigtstd.exe && popd

EIG\xdmdeigtstd.exe: $(FRCEIG) $(FRC)
	pushd EIG && $(MAKE) /NOLOGO /F Makefile.win xdmdeigtstd.exe && popd

EIG\xeigtstz.exe: $(FRCEIG) $(FRC)
	pushd EIG && $(MAKE) /NOLOGO /F Makefile.win xeigtstz.exe && popd

EIG\xdmdeigtstz.exe: $(FRCEIG) $(FRC)
	pushd EIG && $(MAKE) /NOLOGO /F Makefile.win xdmdeigtstz.exe && popd

clean: cleantest

cleantest:
	DEL /F /Q *.out core

FRCLIN:
	@FRCLIN=$(FRCLIN)

FRCEIG:
	@FRCEIG=$(FRCEIG)

FRC:
	@FRC=$(FRC)
