#######################################################################
#  This makefile creates the test programs for the linear equation
#  routines in LAPACK.  The test files are grouped as follows:
#
#       ALINTST -- Auxiliary test routines
#       SLINTST -- Single precision real test routines
#       CLINTST -- Single precision complex test routines
#       SCLNTST -- Single precision real and complex routines in common
#       DLINTST -- Double precision real test routines
#       ZLINTST -- Double precision complex test routines
#       DZLNTST -- Double precision real and complex routines in common
#
#  Test programs can be generated for all or some of the four different
#  precisions.  Enter make followed by one or more of the data types
#  desired.  Some examples:
#       make single
#       make single complex
#       make single double complex complex16
#  Alternatively, the command
#       make
#  without any arguments creates all four test programs.
#  The executable files are called
#       xlintsts, xlintstd, xlintstc, and xlintstz
#
#  To remove the object files after the executable files have been
#  created, enter
#       make cleanobj
#  On some systems, you can force the source files to be recompiled by
#  entering (for example)
#       make single FRC=FRC
#
#######################################################################

TOPSRCDIR = ..\..
!INCLUDE $(TOPSRCDIR)\make.win

.SUFFIXES: .f .obj

.f.obj:
	$(FC) $(FFLAGS) /c /Fo$@ $<

ALINTST = \
   aladhd.obj alaerh.obj alaesm.obj alahd.obj alareq.obj \
   alasum.obj alasvm.obj chkxer.obj icopy.obj ilaenv.obj xlaenv.obj xerbla.obj

SCLNTST = slaord.obj

DZLNTST = dlaord.obj

SLINTST = schkaa.obj \
   schkeq.obj schkgb.obj schkge.obj schkgt.obj \
   schklq.obj schkpb.obj schkpo.obj schkps.obj schkpp.obj \
   schkpt.obj schkq3.obj schkqp3rk.obj schkql.obj schkqr.obj schkrq.obj \
   schksp.obj schksy.obj schksy_rook.obj schksy_rk.obj  \
   schksy_aa.obj schksy_aa_2stage.obj schktb.obj schktp.obj schktr.obj \
   schktz.obj \
   sdrvgt.obj sdrvls.obj sdrvpb.obj \
   sdrvpp.obj sdrvpt.obj sdrvsp.obj sdrvsy_rook.obj sdrvsy_rk.obj \
   sdrvsy_aa.obj sdrvsy_aa_2stage.obj \
   serrgt.obj serrlq.obj serrls.obj \
   serrps.obj serrql.obj serrqp.obj serrqr.obj \
   serrrq.obj serrtr.obj serrtz.obj \
   sgbt01.obj sgbt02.obj sgbt05.obj sgeqls.obj \
   sgerqs.obj sget01.obj sget02.obj \
   sget03.obj sget04.obj sget06.obj sget07.obj sgtt01.obj sgtt02.obj \
   sgtt05.obj slaptm.obj slarhs.obj slatb4.obj slatb5.obj slattb.obj slattp.obj \
   slattr.obj slavsp.obj slavsy.obj slavsy_rook.obj slqt01.obj slqt02.obj \
   slqt03.obj spbt01.obj spbt02.obj spbt05.obj spot01.obj \
   spot02.obj spot03.obj spot05.obj spst01.obj sppt01.obj \
   sppt02.obj sppt03.obj sppt05.obj sptt01.obj sptt02.obj \
   sptt05.obj sqlt01.obj sqlt02.obj sqlt03.obj sqpt01.obj \
   sqrt01.obj sqrt01p.obj sqrt02.obj sqrt03.obj sqrt11.obj sqrt12.obj \
   sqrt13.obj sqrt14.obj sqrt15.obj sqrt16.obj sqrt17.obj \
   srqt01.obj srqt02.obj srqt03.obj srzt01.obj srzt02.obj \
   sspt01.obj ssyt01.obj ssyt01_rook.obj ssyt01_3.obj ssyt01_aa.obj \
   stbt02.obj stbt03.obj stbt05.obj stbt06.obj stpt01.obj \
   stpt02.obj stpt03.obj stpt05.obj stpt06.obj strt01.obj \
   strt02.obj strt03.obj strt05.obj strt06.obj \
   sgennd.obj sqrt04.obj sqrt05.obj schkqrt.obj serrqrt.obj schkqrtp.obj serrqrtp.obj \
   schklqt.obj schklqtp.obj schktsqr.obj \
   serrlqt.obj serrlqtp.obj serrtsqr.obj stsqr01.obj slqt04.obj slqt05.obj \
   schkorhr_col.obj serrorhr_col.obj sorhr_col01.obj sorhr_col02.obj \
   sdrvgb.obj sdrvge.obj sdrvsy.obj sdrvpo.obj \
   serrvx.obj serrge.obj serrsy.obj serrpo.obj

CLINTST = cchkaa.obj \
   cchkeq.obj cchkgb.obj cchkge.obj cchkgt.obj \
   cchkhe.obj cchkhe_rook.obj cchkhe_rk.obj  \
   cchkhe_aa.obj cchkhe_aa_2stage.obj cchkhp.obj cchklq.obj cchkpb.obj \
   cchkpo.obj cchkps.obj cchkpp.obj cchkpt.obj cchkq3.obj cchkqp3rk.obj cchkql.obj \
   cchkqr.obj cchkrq.obj cchksp.obj cchksy.obj cchksy_rook.obj cchksy_rk.obj \
   cchksy_aa.obj cchksy_aa_2stage.obj cchktb.obj \
   cchktp.obj cchktr.obj cchktz.obj \
   cdrvgt.obj cdrvhe_rook.obj cdrvhe_rk.obj cdrvhe_aa.obj cdrvhp.obj \
   cdrvhe_aa_2stage.obj \
   cdrvls.obj cdrvpb.obj cdrvpp.obj cdrvpt.obj \
   cdrvsp.obj cdrvsy_rook.obj cdrvsy_rk.obj cdrvsy_aa.obj cdrvsy_aa_2stage.obj \
   cerrgt.obj cerrlq.obj \
   cerrls.obj cerrps.obj cerrql.obj cerrqp.obj \
   cerrqr.obj cerrrq.obj cerrtr.obj cerrtz.obj \
   cgbt01.obj cgbt02.obj cgbt05.obj cgeqls.obj \
   cgerqs.obj cget01.obj cget02.obj \
   cget03.obj cget04.obj cget07.obj cgtt01.obj cgtt02.obj \
   cgtt05.obj chet01.obj chet01_rook.obj chet01_3.obj chet01_aa.obj \
   chpt01.obj claipd.obj claptm.obj clarhs.obj clatb4.obj clatb5.obj \
   clatsp.obj clatsy.obj clattb.obj clattp.obj clattr.obj \
   clavhe.obj clavhe_rook.obj clavhp.obj clavsp.obj clavsy.obj clavsy_rook.obj clqt01.obj \
   clqt02.obj clqt03.obj cpbt01.obj cpbt02.obj cpbt05.obj \
   cpot01.obj cpot02.obj cpot03.obj cpot05.obj cpst01.obj \
   cppt01.obj cppt02.obj cppt03.obj cppt05.obj cptt01.obj \
   cptt02.obj cptt05.obj cqlt01.obj cqlt02.obj cqlt03.obj \
   cqpt01.obj cqrt01.obj cqrt01p.obj cqrt02.obj cqrt03.obj cqrt11.obj \
   cqrt12.obj cqrt13.obj cqrt14.obj cqrt15.obj cqrt16.obj \
   cqrt17.obj crqt01.obj crqt02.obj crqt03.obj crzt01.obj crzt02.obj \
   csbmv.obj  cspt01.obj \
   cspt02.obj cspt03.obj csyt01.obj csyt01_rook.obj csyt01_3.obj csyt01_aa.obj csyt02.obj csyt03.obj \
   ctbt02.obj ctbt03.obj ctbt05.obj ctbt06.obj ctpt01.obj \
   ctpt02.obj ctpt03.obj ctpt05.obj ctpt06.obj ctrt01.obj \
   ctrt02.obj ctrt03.obj ctrt05.obj ctrt06.obj \
   sget06.obj cgennd.obj \
   cqrt04.obj cqrt05.obj cchkqrt.obj cerrqrt.obj cchkqrtp.obj cerrqrtp.obj \
   cchklqt.obj cchklqtp.obj cchktsqr.obj \
   cerrlqt.obj cerrlqtp.obj cerrtsqr.obj ctsqr01.obj clqt04.obj clqt05.obj \
   cchkunhr_col.obj cerrunhr_col.obj cunhr_col01.obj cunhr_col02.obj \
   cdrvgb.obj cdrvge.obj cdrvhe.obj cdrvsy.obj cdrvpo.obj \
   cerrvx.obj cerrge.obj cerrhe.obj cerrsy.obj cerrpo.obj

DLINTST = dchkaa.obj \
   dchkeq.obj dchkgb.obj dchkge.obj dchkgt.obj \
   dchklq.obj dchkpb.obj dchkpo.obj dchkps.obj dchkpp.obj \
   dchkpt.obj dchkq3.obj dchkqp3rk.obj dchkql.obj dchkqr.obj dchkrq.obj \
   dchksp.obj dchksy.obj dchksy_rook.obj dchksy_rk.obj  \
   dchksy_aa.obj dchksy_aa_2stage.obj dchktb.obj dchktp.obj dchktr.obj \
   dchktz.obj \
   ddrvgt.obj ddrvls.obj ddrvpb.obj \
   ddrvpp.obj ddrvpt.obj ddrvsp.obj ddrvsy_rook.obj ddrvsy_rk.obj \
   ddrvsy_aa.obj ddrvsy_aa_2stage.obj \
   derrgt.obj derrlq.obj derrls.obj \
   derrps.obj derrql.obj derrqp.obj derrqr.obj \
   derrrq.obj derrtr.obj derrtz.obj \
   dgbt01.obj dgbt02.obj dgbt05.obj dgeqls.obj \
   dgerqs.obj dget01.obj dget02.obj \
   dget03.obj dget04.obj dget06.obj dget07.obj dgtt01.obj dgtt02.obj \
   dgtt05.obj dlaptm.obj dlarhs.obj dlatb4.obj dlatb5.obj dlattb.obj dlattp.obj \
   dlattr.obj dlavsp.obj dlavsy.obj dlavsy_rook.obj dlqt01.obj dlqt02.obj \
   dlqt03.obj dpbt01.obj dpbt02.obj dpbt05.obj dpot01.obj \
   dpot02.obj dpot03.obj dpot05.obj dpst01.obj dppt01.obj \
   dppt02.obj dppt03.obj dppt05.obj dptt01.obj dptt02.obj \
   dptt05.obj dqlt01.obj dqlt02.obj dqlt03.obj dqpt01.obj \
   dqrt01.obj dqrt01p.obj dqrt02.obj dqrt03.obj dqrt11.obj dqrt12.obj \
   dqrt13.obj dqrt14.obj dqrt15.obj dqrt16.obj dqrt17.obj \
   drqt01.obj drqt02.obj drqt03.obj drzt01.obj drzt02.obj \
   dspt01.obj dsyt01.obj dsyt01_rook.obj dsyt01_3.obj dsyt01_aa.obj \
   dtbt02.obj dtbt03.obj dtbt05.obj dtbt06.obj dtpt01.obj \
   dtpt02.obj dtpt03.obj dtpt05.obj dtpt06.obj dtrt01.obj \
   dtrt02.obj dtrt03.obj dtrt05.obj dtrt06.obj \
   dgennd.obj \
   dqrt04.obj dqrt05.obj dchkqrt.obj derrqrt.obj dchkqrtp.obj derrqrtp.obj \
   dchklq.obj dchklqt.obj dchklqtp.obj dchktsqr.obj \
   derrlqt.obj derrlqtp.obj derrtsqr.obj dtsqr01.obj dlqt04.obj dlqt05.obj \
   dchkorhr_col.obj derrorhr_col.obj dorhr_col01.obj dorhr_col02.obj \
   ddrvgb.obj ddrvge.obj ddrvsy.obj ddrvpo.obj \
   derrvx.obj derrge.obj derrsy.obj derrpo.obj

ZLINTST = zchkaa.obj \
   zchkeq.obj zchkgb.obj zchkge.obj zchkgt.obj \
   zchkhe.obj zchkhe_rook.obj zchkhe_rk.obj zchkhe_aa.obj zchkhe_aa_2stage.obj \
   zchkhp.obj zchklq.obj zchkpb.obj \
   zchkpo.obj zchkps.obj zchkpp.obj zchkpt.obj zchkq3.obj zchkqp3rk.obj zchkql.obj \
   zchkqr.obj zchkrq.obj zchksp.obj zchksy.obj zchksy_rook.obj zchksy_rk.obj \
   zchksy_aa.obj zchksy_aa_2stage.obj zchktb.obj \
   zchktp.obj zchktr.obj zchktz.obj \
   zdrvgt.obj zdrvhe_rook.obj zdrvhe_rk.obj zdrvhe_aa.obj zdrvhe_aa_2stage.obj zdrvhp.obj \
   zdrvls.obj zdrvpb.obj zdrvpp.obj zdrvpt.obj \
   zdrvsp.obj zdrvsy_rook.obj zdrvsy_rk.obj zdrvsy_aa.obj zdrvsy_aa_2stage.obj \
   zerrgt.obj zerrlq.obj \
   zerrls.obj zerrps.obj zerrql.obj zerrqp.obj \
   zerrqr.obj zerrrq.obj zerrtr.obj zerrtz.obj \
   zgbt01.obj zgbt02.obj zgbt05.obj zgeqls.obj \
   zgerqs.obj zget01.obj zget02.obj \
   zget03.obj zget04.obj zget07.obj zgtt01.obj zgtt02.obj \
   zgtt05.obj zhet01.obj zhet01_rook.obj zhet01_3.obj zhet01_aa.obj \
   zhpt01.obj zlaipd.obj zlaptm.obj zlarhs.obj zlatb4.obj zlatb5.obj \
   zlatsp.obj zlatsy.obj zlattb.obj zlattp.obj zlattr.obj \
   zlavhe.obj zlavhe_rook.obj zlavhp.obj zlavsp.obj zlavsy.obj zlavsy_rook.obj zlqt01.obj \
   zlqt02.obj zlqt03.obj zpbt01.obj zpbt02.obj zpbt05.obj \
   zpot01.obj zpot02.obj zpot03.obj zpot05.obj zpst01.obj \
   zppt01.obj zppt02.obj zppt03.obj zppt05.obj zptt01.obj \
   zptt02.obj zptt05.obj zqlt01.obj zqlt02.obj zqlt03.obj \
   zqpt01.obj zqrt01.obj zqrt01p.obj zqrt02.obj zqrt03.obj zqrt11.obj \
   zqrt12.obj zqrt13.obj zqrt14.obj zqrt15.obj zqrt16.obj \
   zqrt17.obj zrqt01.obj zrqt02.obj zrqt03.obj zrzt01.obj zrzt02.obj \
   zsbmv.obj  zspt01.obj \
   zspt02.obj zspt03.obj zsyt01.obj zsyt01_rook.obj zsyt01_3.obj zsyt01_aa.obj zsyt02.obj zsyt03.obj \
   ztbt02.obj ztbt03.obj ztbt05.obj ztbt06.obj ztpt01.obj \
   ztpt02.obj ztpt03.obj ztpt05.obj ztpt06.obj ztrt01.obj \
   ztrt02.obj ztrt03.obj ztrt05.obj ztrt06.obj \
   dget06.obj zgennd.obj \
   zqrt04.obj zqrt05.obj zchkqrt.obj zerrqrt.obj zchkqrtp.obj zerrqrtp.obj \
   zchklqt.obj zchklqtp.obj zchktsqr.obj \
   zerrlqt.obj zerrlqtp.obj zerrtsqr.obj ztsqr01.obj zlqt04.obj zlqt05.obj \
   zchkunhr_col.obj zerrunhr_col.obj zunhr_col01.obj zunhr_col02.obj \
   zdrvgb.obj zdrvge.obj zdrvhe.obj zdrvsy.obj zdrvpo.obj \
   zerrvx.obj zerrge.obj zerrhe.obj zerrsy.obj zerrpo.obj

DSLINTST = dchkab.obj \
	ddrvab.obj ddrvac.obj derrab.obj derrac.obj dget08.obj \
	alaerh.obj alahd.obj  aladhd.obj alareq.obj \
	chkxer.obj dlarhs.obj dlatb4.obj xerbla.obj \
	dget02.obj dpot06.obj

ZCLINTST = zchkab.obj \
	zdrvab.obj zdrvac.obj zerrab.obj zerrac.obj zget08.obj \
	alaerh.obj alahd.obj  aladhd.obj alareq.obj \
	chkxer.obj zget02.obj zlarhs.obj zlatb4.obj \
	zsbmv.obj  xerbla.obj zpot06.obj zlaipd.obj

SLINTSTRFP = schkrfp.obj sdrvrfp.obj sdrvrf1.obj sdrvrf2.obj sdrvrf3.obj sdrvrf4.obj serrrfp.obj \
	slatb4.obj slarhs.obj sget04.obj spot01.obj spot03.obj spot02.obj \
	chkxer.obj xerbla.obj alaerh.obj aladhd.obj alahd.obj alasvm.obj

DLINTSTRFP = dchkrfp.obj ddrvrfp.obj ddrvrf1.obj ddrvrf2.obj ddrvrf3.obj ddrvrf4.obj derrrfp.obj \
	dlatb4.obj dlarhs.obj dget04.obj dpot01.obj dpot03.obj dpot02.obj \
	chkxer.obj xerbla.obj alaerh.obj aladhd.obj alahd.obj alasvm.obj

CLINTSTRFP = cchkrfp.obj cdrvrfp.obj cdrvrf1.obj cdrvrf2.obj cdrvrf3.obj cdrvrf4.obj cerrrfp.obj \
	claipd.obj clatb4.obj clarhs.obj csbmv.obj cget04.obj cpot01.obj cpot03.obj cpot02.obj \
	chkxer.obj xerbla.obj alaerh.obj aladhd.obj alahd.obj alasvm.obj

ZLINTSTRFP = zchkrfp.obj zdrvrfp.obj zdrvrf1.obj zdrvrf2.obj zdrvrf3.obj zdrvrf4.obj zerrrfp.obj \
	zlatb4.obj zlaipd.obj zlarhs.obj zsbmv.obj zget04.obj zpot01.obj zpot03.obj zpot02.obj \
	chkxer.obj xerbla.obj alaerh.obj aladhd.obj alahd.obj alasvm.obj

all: single double complex complex16 proto-single proto-double proto-complex proto-complex16

single: xlintsts.exe
double: xlintstd.exe
complex: xlintstc.exe
complex16: xlintstz.exe

proto-single: xlintstrfs.exe
proto-double: xlintstds.exe xlintstrfd.exe
proto-complex: xlintstrfc.exe
proto-complex16: xlintstzc.exe xlintstrfz.exe

xlintsts.exe: $(ALINTST) $(SLINTST) $(SCLNTST) $(TMGLIB) $(VARLIB) $(LAPACKLIB) $(XBLASLIB) $(BLASLIB)
	$(FC) $(FFLAGS) /Fe$@ $** $(LDFLAGS)

xlintstc.exe: $(ALINTST) $(CLINTST) $(SCLNTST) $(TMGLIB) $(VARLIB) $(LAPACKLIB) $(XBLASLIB) $(BLASLIB)
	$(FC) $(FFLAGS) /Fe$@ $** $(LDFLAGS)

xlintstd.exe: $(ALINTST) $(DLINTST) $(DZLNTST) $(TMGLIB) $(VARLIB) $(LAPACKLIB) $(XBLASLIB) $(BLASLIB)
	$(FC) $(FFLAGS) /Fe$@ $** $(LDFLAGS)

xlintstz.exe: $(ALINTST) $(ZLINTST) $(DZLNTST) $(TMGLIB) $(VARLIB) $(LAPACKLIB) $(XBLASLIB) $(BLASLIB)
	$(FC) $(FFLAGS) /Fe$@ $** $(LDFLAGS)

xlintstds.exe: $(DSLINTST) $(TMGLIB) $(VARLIB) $(LAPACKLIB) $(BLASLIB)
	$(FC) $(FFLAGS) /Fe$@ $** $(LDFLAGS)

xlintstzc.exe: $(ZCLINTST) $(TMGLIB) $(VARLIB) $(LAPACKLIB) $(BLASLIB)
	$(FC) $(FFLAGS) /Fe$@ $** $(LDFLAGS)

xlintstrfs.exe: $(SLINTSTRFP) $(TMGLIB) $(VARLIB) $(LAPACKLIB) $(BLASLIB)
	$(FC) $(FFLAGS) /Fe$@ $** $(LDFLAGS)

xlintstrfd.exe: $(DLINTSTRFP) $(TMGLIB) $(VARLIB) $(LAPACKLIB) $(BLASLIB)
	$(FC) $(FFLAGS) /Fe$@ $** $(LDFLAGS)

xlintstrfc.exe: $(CLINTSTRFP) $(TMGLIB) $(VARLIB) $(LAPACKLIB) $(BLASLIB)
	$(FC) $(FFLAGS) /Fe$@ $** $(LDFLAGS)

xlintstrfz.exe: $(ZLINTSTRFP) $(TMGLIB) $(VARLIB) $(LAPACKLIB) $(BLASLIB)
	$(FC) $(FFLAGS) /Fe$@ $** $(LDFLAGS)

$(ALINTST): $(FRC)
$(SCLNTST): $(FRC)
$(DZLNTST): $(FRC)
$(SLINTST): $(FRC)
$(CLINTST): $(FRC)
$(DLINTST): $(FRC)
$(ZLINTST): $(FRC)

FRC:
	@FRC=$(FRC)

clean: cleanobj cleanexe

cleanobj:
	DEL /F /Q *.obj

cleanexe:
	DEL /F /Q xlintst*.exe

schkaa.obj: schkaa.F
	$(FC) $(FFLAGS_DRV) /c /Fo$@ $**
dchkaa.obj: dchkaa.F
	$(FC) $(FFLAGS_DRV) /c /Fo$@ $**
cchkaa.obj: cchkaa.F
	$(FC) $(FFLAGS_DRV) /c /Fo$@ $**
zchkaa.obj: zchkaa.F
	$(FC) $(FFLAGS_DRV) /c /Fo$@ $**
